### PR TITLE
Fix comments button

### PR DESCRIPTION
**Pull request by volkov97**

### CODE REVIEW

**Comment by volkov97** [comment]
I can't understand why translations of block 'comments' here are not working.
It is also not working at master brunch now.

**Comment by volkov97** [comment]
It also fixes viewing post page when user is not logged in.

**Comment by volkov97** [comment]
How it looks when there are no comments.
https://yadi.sk/i/dmyzn9EL3Kdcx3

**Review by tadatuta — APPROVED** [review]
LGTM

**Pull request merged**
